insert into photo (id, filename)
values  (1, 'windbreakerHunneboUnisexNavy.webp'),
        (3, 'windbreakerHunneboUnisexOffwhite.webp'),
        (4, 'windbreakerJackeBovallUnisexGreen.webp'),
        (5, 'windbreakerJackeBovallUnisexGrey.webp'),
        (6, 'windbreakerJackeBovallUnisexNavy.webp'),
        (7, 'windbreakerJackeBovallUnisexOffwhite.webp'),
        (8, 'windbreakerJackeBovallUnisexRed.webp'),
        (9, 'windbreakerJackeKungshamnUnisexBlack.webp'),
        (10, 'windbreakerJackeKungshamnUnisexRed.webp'),
        (11, 'windbreakerLyckeUnisexNavy.webp'),
        (12, 'windbreakerLyckeUnisexRed.webp'),
        (13, 'windbreakerLysekilJuniorBlack.webp'),
        (14, 'windbreakerLysekilJuniorNavy.webp'),
        (15, 'windbreakerLysekilJuniorRed.webp'),
        (16, 'windbreakerLysekilUnisexBlack.webp'),
        (17, 'windbreakerLysekilUnisexGrey.webp'),
        (18, 'windbreakerLysekilUnisexNavy.webp'),
        (19, 'windbreakerLysekilUnisexNavy1.webp'),
        (20, 'windbreakerLysekilUnisexNavy2.webp'),
        (21, 'windbreakerLysekilUnisexNavy3.webp'),
        (22, 'windbreakerLysekilUnisexNavy4.webp'),
        (23, 'windbreakerLysekilUnisexNavy5.webp'),
        (24, 'windbreakerLysekilUnisexOffwhite.webp'),
        (25, 'windbreakerLysekilUnisexRed.webp');